apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sealed-secrets-monitor.configMapName" . }}
  labels:
    {{- include "sealed-secrets-monitor.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  namespace: "{{ .Release.Namespace }}"
  wait_for_secrets.sh: |
    #!/bin/bash
    LIST=( $(kubectl get SealedSecret -n "${NAMESPACE}" -o jsonpath='{.items[*].metadata.name}') )
    LOOP_COUNT=0
    while [ ${#LIST[@]} -gt 0 ]; do
      ((LOOP_COUNT++))
      echo "Starting loop ${LOOP_COUNT}, checking ${#LIST[@]} secrets."
      sleep 5
      REMAINING=()
      COUNT=0
      for SECRET in "${LIST[@]}"; do
        if ! kubectl get secret "${SECRET}" -n "${NAMESPACE}" &>/dev/null ; then
          REMAINING+=($SECRET)
        else
          ((COUNT++))
        fi
      done
      echo "Found ${COUNT} secrets"
      LIST=("${REMAINING[@]}")
    done
    echo "All sealed secrets have been decrypted"
