apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sealed-secrets-monitor.roleBindingName" . }}
  labels:
    {{- include "sealed-secrets-monitor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sealed-secrets-monitor.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "sealed-secrets-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
