# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
- package-ecosystem: "helm"
  directories:
    - "/charts/*"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

registries:
  dockerio: # Define access for a private registry
    type: docker-registry
    url: docker.io
    username: joernott
    password: ${{secrets.DOCKERHUB_PASSWORD}}
  dockercom: # Define access for a private registry
    type: docker-registry
    url: docker.com
    username: joernott
    password: ${{secrets.DOCKERHUB_PASSWORD}}
