---
repos:
  - repo: https://github.com/dadav/helm-schema
    rev: 0.18.1
    hooks:
      - id: helm-schema
        # for all available options: helm-schema -h
        args:
          # directory to search recursively within for charts
          - --chart-search-root=charts

          # don't analyze dependencies
          - --no-dependencies

          # add references to values file if not exist
          - --add-schema-reference

          # use in conjunction with helm-docs
          - --helm-docs-compatibility-mode

          # list of fields to skip from being created by default
          # e.g. generate a relatively permissive schema
          # - "--skip-auto-generation=required,additionalProperties"

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl